create table instruments (
	id INT GENERATED ALWAYS AS  IDENTITYNOT NULL,
	brand VARCHAR(500),
	rent_fee VARCHAR(500),
);
insert into instrumments (id, brand, rent_fee) values (1, 'Veribet', 756);
insert into instrumments (id, brand, rent_fee) values (2, 'Bigtax', 339);
insert into instrumments (id, brand, rent_fee) values (3, 'Subin', 533);
insert into instrumments (id, brand, rent_fee) values (4, 'Veribet', 826);
insert into instrumments (id, brand, rent_fee) values (5, 'Bigtax', 206);
insert into instrumments (id, brand, rent_fee) values (6, 'Rank', 1);
insert into instrumments (id, brand, rent_fee) values (7, 'Bigtax', 622);
insert into instrumments (id, brand, rent_fee) values (8, 'Bigtax', 205);
insert into instrumments (id, brand, rent_fee) values (9, 'Veribet', 517);
insert into instrumments (id, brand, rent_fee) values (10, 'Matsoft', 581);
insert into instrumments (id, brand, rent_fee) values (11, 'Bigtax', 329);
insert into instrumments (id, brand, rent_fee) values (12, 'Rank', 250);
insert into instrumments (id, brand, rent_fee) values (13, 'Veribet', 399);
insert into instrumments (id, brand, rent_fee) values (14, 'Subin', 403);
insert into instrumments (id, brand, rent_fee) values (15, 'Matsoft', 369);
insert into instrumments (id, brand, rent_fee) values (16, 'Rank', 407);
insert into instrumments (id, brand, rent_fee) values (17, 'Gembucket', 566);
insert into instrumments (id, brand, rent_fee) values (18, 'Rank', 249);
insert into instrumments (id, brand, rent_fee) values (19, 'Matsoft', 390);
insert into instrumments (id, brand, rent_fee) values (20, 'Subin', 727);
insert into instrumments (id, brand, rent_fee) values (21, 'Subin', 356);
insert into instrumments (id, brand, rent_fee) values (22, 'Gembucket', 324);
insert into instrumments (id, brand, rent_fee) values (23, 'Rank', 585);
insert into instrumments (id, brand, rent_fee) values (24, 'Bigtax', 193);
insert into instrumments (id, brand, rent_fee) values (25, 'Bigtax', 756);
insert into instrumments (id, brand, rent_fee) values (26, 'Bigtax', 970);
insert into instrumments (id, brand, rent_fee) values (27, 'Rank', 542);
insert into instrumments (id, brand, rent_fee) values (28, 'Bigtax', 334);
insert into instrumments (id, brand, rent_fee) values (29, 'Bigtax', 951);
insert into instrumments (id, brand, rent_fee) values (30, 'Gembucket', 360);
insert into instrumments (id, brand, rent_fee) values (31, 'Gembucket', 973);
insert into instrumments (id, brand, rent_fee) values (32, 'Subin', 753);
insert into instrumments (id, brand, rent_fee) values (33, 'Subin', 772);
insert into instrumments (id, brand, rent_fee) values (34, 'Rank', 303);
insert into instrumments (id, brand, rent_fee) values (35, 'Rank', 559);
insert into instrumments (id, brand, rent_fee) values (36, 'Gembucket', 747);
insert into instrumments (id, brand, rent_fee) values (37, 'Veribet', 723);
insert into instrumments (id, brand, rent_fee) values (38, 'Bigtax', 374);
insert into instrumments (id, brand, rent_fee) values (39, 'Bigtax', 173);
insert into instrumments (id, brand, rent_fee) values (40, 'Rank', 531);
insert into instrumments (id, brand, rent_fee) values (41, 'Subin', 840);
insert into instrumments (id, brand, rent_fee) values (42, 'Bigtax', 707);
insert into instrumments (id, brand, rent_fee) values (43, 'Matsoft', 841);
insert into instrumments (id, brand, rent_fee) values (44, 'Matsoft', 69);
insert into instrumments (id, brand, rent_fee) values (45, 'Veribet', 55);
insert into instrumments (id, brand, rent_fee) values (46, 'Subin', 457);
insert into instrumments (id, brand, rent_fee) values (47, 'Bigtax', 772);
insert into instrumments (id, brand, rent_fee) values (48, 'Matsoft', 462);
insert into instrumments (id, brand, rent_fee) values (49, 'Veribet', 640);
insert into instrumments (id, brand, rent_fee) values (50, 'Matsoft', 269);
