create table instruments_type (
	instrument_teaches_type VARCHAR(14),
	instructor_id INT
);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('piano & guitar', 1);
insert into instruments_type (instrument_teaches_type, instructor_id) values ('guitar', 2);
